page_title                                : Wand

presskit_download_link                    : https://junhoyeo.github.io/wand-prototype/
app_icon                                  : assets/appicon.png
app_name                                  : Wand
app_price                                 : 무료
app_description                           : 오피스 공간의 생산성을 높이다.

enable_smart_app_banner                   : true

email_address                             : hanaro0704@gmail.com
facebook_username                         : inudevs
github_username                           : inudevs

# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : 건물 스마트 지도 제공
    description                           : 건물의 도면을 바탕으로 스마트 지도를 제작, 제공합니다.
    fontawesome_icon_name                 : magic
    
  - title                                 : 통합 모바일 애플리케이션 제공
    description                           : Wand의 모든 건물, 모든 서비스를 누릴 수 있는 애플리케이션을 제공합니다.
    fontawesome_icon_name                 : mobile

  - title                                 : 건물 정보 제공
    description                           : 건물과 각 공간에 대한 정보와 부가 서비스를 제공합니다.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#23453C"
cover_overlay_transparency                : 0.8

device_color                              : black

body_background_color                     : "#ffffff"

link_color                                : "#45BA9B"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#45BA9B"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown